"""Generate the Web email fold from the unchanged Python authentication authority.

Requires Python 3.12 / Unicode 15.0.0, using only the standard library.
Run this file to regenerate src/email-casefold-data.ts; --check compares the
committed artifact without writing it. --stdout prints the same artifact.
Default full casefold is deliberately not lowercase, locale folding, or NFKC.
"""

import argparse
import json
import sys
import unicodedata
from pathlib import Path


def generated_data():
    if sys.version_info[:2] != (3, 12) or unicodedata.unidata_version != "15.0.0":
        raise SystemExit("Email casefold generation requires Python 3.12 / Unicode 15.0.0")
    lines = [
        "// Generated by generate-email-casefold.py from Python 3.12 str.casefold().",
        "// Unicode 15.0.0 default full casefold; regenerate, do not edit manually.",
        "export const CASEFOLD_UNICODE_VERSION = '15.0.0';",
        "export const FULL_CASEFOLD: Readonly<Record<string, string>> = {",
    ]
    for codepoint in range(0x110000):
        character = chr(codepoint)
        folded = character.casefold()
        if folded != character:
            lines.append(f"  {json.dumps(character, ensure_ascii=True)}: {json.dumps(folded, ensure_ascii=True)},")
    lines.extend(["};", ""])
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    modes = parser.add_mutually_exclusive_group()
    modes.add_argument("--stdout", action="store_true")
    modes.add_argument("--check", action="store_true")
    options = parser.parse_args()
    content = generated_data()
    destination = Path(__file__).resolve().parent / "src" / "email-casefold-data.ts"
    if options.stdout:
        sys.stdout.write(content)
    elif options.check:
        if not destination.is_file() or destination.read_text(encoding="utf-8") != content:
            raise SystemExit("Generated email casefold data differs; regenerate with Python 3.12")
    else:
        destination.write_text(content, encoding="utf-8")


if __name__ == "__main__":
    main()
